name: frigate-with-tailscale

networks:
  frigate-net:
    driver: bridge

services:
  frigate-ts:
    image: tailscale/tailscale:latest
    container_name: frigate-ts
    hostname: frigate-ts
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve-config.json
      - TS_USERSPACE=false
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - ./config/tailscale/serve-config.json:/config/serve-config.json
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    networks:
      - frigate-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    shm_size: '256mb'
    volumes:
      - frigate-config:/config
      - frigate-storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - TZ=Asia/Kathmandu
    networks:
      - frigate-net
    restart: unless-stopped
    depends_on:
      frigate-ts:
        condition: service_healthy

volumes:
  tailscale-state:
    driver: local
    driver_opts:
      type: none
      device: /mnt/frigate/tailscale-state
      o: bind
  frigate-config:
    driver: local
    driver_opts:
      type: none
      device: /mnt/frigate/frigate-config
      o: bind
  frigate-storage:
    driver: local
    driver_opts:
      type: none
      device: /mnt/frigate/frigate-storage
      o: bind